try:
    print(a)
except NameError:
    print("Name exception occured")